site_name: AudioMuse-AI Documentation
# This tells MkDocs to look for your Markdown content in the project root.
docs_dir: /web

site_url: https://neptunehub.github.io/AudioMuse-AI/
repo_url: https://github.com/NeptuneHub/AudioMuse-AI
repo_name: GitHub

# Remove the 'nav' section entirely to let MkDocs auto-generate the menu.
# It will typically find 'README.md' as the default page.

use_directory_urls: false # To prevent URL doubling and use .html extensions

theme:
  name: readthedocs # Your chosen theme.

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - md_in_html
