name: Build ARM Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile.arm'
      - '.github/workflows/build-arm.yml'
      - '**/*.py'
      - 'deplyment/**'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image for ARM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ARM image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.arm
          push: true
          platforms: linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/audiomuse-arm:latest
