name: Build and Deploy Site from web dir to gh-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Copy README to build directory
        run: cp README.md web/

      - name: Setup Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
          working-directory: ./web

      - name: Build the Jekyll site
        run: bundle exec jekyll build --destination ./_site
        working-directory: ./web
        env:
          JEKYLL_ENV: production

      - name: Deploy to gh-pages branch
        uses: actions/deploy-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./web/_site
