name: Build and Push AudioMuse AI Docker Image

on:
  push:
    branches:
      - main        # Trigger for 'latest'
      - development # Trigger for 'devel'
    tags:
      - 'v*.*.*'    # Trigger for version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker image tags
        id: docker_tags
        run: |
          REPO_NAME_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          ALL_TAGS=""

          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            MAIN_TAG="ghcr.io/$REPO_NAME_LOWER:latest"
            ALL_TAGS="$MAIN_TAG"
            echo "Building latest tag: $MAIN_TAG"

          elif [[ "${GITHUB_REF}" == "refs/heads/devel" ]]; then
            DEV_TAG="ghcr.io/$REPO_NAME_LOWER:devel"
            ALL_TAGS="$DEV_TAG"
            echo "Building devel tag: $DEV_TAG"

          elif [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION_TAG=$(echo "${GITHUB_REF}" | sed -e 's|refs/tags/v||g')
            VERSIONED_TAG="ghcr.io/$REPO_NAME_LOWER:${VERSION_TAG}"
            ALL_TAGS="$VERSIONED_TAG"
            echo "Building versioned tag: $VERSIONED_TAG"
          fi

          echo "docker_tags=$ALL_TAGS" >> "$GITHUB_OUTPUT"

      - name: Build and Push AudioMuse AI Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.docker_tags.outputs.docker_tags }}
