# .github/workflows/release-helm-chart.yml

name: Release Helm Chart

on:
  push:
    branches:
      - main
      - devel

jobs:
  release:
    # Grant permissions to create a GitHub Release and push to the gh-pages branch.
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set target branch
        id: branch
        run: echo "target=$(if [[ \"${GITHUB_REF}\" == \"refs/heads/devel\" ]]; then echo devel; else echo main; fi)" >> $GITHUB_OUTPUT

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: helm-chart
          target_branch: ${{ steps.branch.outputs.target }}
          prerelease: ${{ github.ref == 'refs/heads/devel' }}
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
