# .github/workflows/release-helm-chart.yml

name: Release Helm Chart

on:
  push:
    branches:
      - main
      - devel

jobs:
  release:
    # Grant permissions to create a GitHub Release and push to the gh-pages branch.
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetches all history for all branches and tags, which is required
          # by the chart-releaser action to determine changes.
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.1 # Updated to a version that supports 'prerelease'
        with:
          # The path to the chart directory.
          charts_dir: helm-chart
          # If the push is to the 'devel' branch, mark the GitHub Release as a pre-release.
          target_branch: main # <--- Add this line
          # Otherwise, it will be a full release.
          prerelease: ${{ github.ref == 'refs/heads/devel' }}
        env:
          # The chart-releaser action uses this token to create releases and push to gh-pages.
          # GITHUB_TOKEN is automatically provided by GitHub Actions.
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"