name: Unit Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy
        # Install minimal requirements for unit tests
        if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi

    - name: Run unit tests
      run: |
        pytest tests/unit/ -v
