title: AudioMuse-AI Documentation
description: "Documentation for the AudioMuse-AI project."
baseurl: "/AudioMuse-AI"
url: "https://NeptuneHub.github.io"

# Tell Jekyll to treat the '_sections' directory as a collection of documents
collections:
  sections:
    output: true # Generate a page for each document in the collection
    sort_by: order # Sort the pages by the 'order' variable in their front matter
