title: AudioMuse-AI Documentation
description: "Documentation for the AudioMuse-AI project."
baseurl: "/AudioMuse-AI"
url: "https://NeptuneHub.github.io"

include:
  - "README.md"

multipage_auto_pagebreak_at_headings: true
multipage_auto_pagebreak_heading_level: 2

plugins:
  - jekyll-multipage
